---
- name: Demo playbook for loops
  hosts: node1
  become: true
  vars:
    user_and_group_list:
      - username: dev_user
        group: ftp
      - username: qa_user
        group: apache
      - username: prod_user
        group: admin
  tasks:
    - name: Ensure all groups are created
      ansible.builtin.group:
        name: "{{ item.group }}"
        state: present
      loop: "{{ user_and_group_list }}"
    - name: Ensure multiple users are present
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.group }}"
        state: present
        append: true
      loop: "{{ user_and_group_list }}"

